bettyblocks/material-ui-component-set

src/components/checkbox.js
src/prefabs/checkbox.js

- Set default label
- Add size option
- Add helper text option
- Remove full-width option

Change some options of checkbox

---

src/components/dateTimePicker.js
src/prefabs/dateTimePicker.js

this also includes timepicker and datetimepicker

feat: add datepicker

---

src/prefabs/form.js

Reverts bettyblocks/material-ui-component-set#152

Revert "Feat/add custom model generation to form ta 1413"

---

src/components/dataList.js
src/prefabs/dataList.js

Add a custom button group to choose between list and grid view. You can set a width for the grid items and the gap between the grid items.

Responsive show as grid option for data list

---

src/components/alert.js
src/prefabs/alert.js

feat: add alignment options to alert

---

src/components/container.js

in dev it didn't show the correct height because of the extra wrapper

fix: container height option

---

src/components/dateTimePicker.js
src/prefabs/dateTimePicker.js

feat: add feature flag for 24 hour support
fix: set default date format in EU styling

feat: make date picker compatible with backend time format

---

src/components/button.js

Fixed button break when using a form inside the pagebuilder (mapping error)

Fixed button break when using a form inside the pagebuilder

---

src/components/autoComplete.js
src/components/checkbox.js
src/components/radio.js
src/components/select.js
src/prefabs/select.js

This enables list property values to be shown in the form select component.
should these values be able to be overriden by the `selectOptions`?

fix: show list property values in the dropdown when a listproperty is selected

---

src/components/checkbox.js
src/components/radio.js
yarn.lock

add `onChange` trigger to checkbox and radio components.

add onChange triggers to checkbox and radio

---

CHANGELOG.md
package.json
src/components/expansionPanel.js

Fixed by changing onClick function to panel summary, instead of entire panel.

Fix expantion panel bug TA-1854

---

.eslintrc.json
src/components/dataContainer.js
src/components/dataList.js
src/components/dataTable.js
src/interactions/setCurrentRecord.ts
src/prefabs/dataContainer.js
src/prefabs/dataList.js
src/prefabs/dataTable.js

- add logic to data container to read from currentRecord
only reads from option if no filter was manually set
- add rowClick event to data list
- add currentRow option to data list
- add currentRow option to data table
- add new default global function

feat: allow linking between data container and list and table views

---

src/components/form.js

This pr adds the records' id to a form post (if it exists) as `id`, preventing the need to add hidden inputs for simple update/delete actions within forms. Related Jira ticket can be found  [here](https://bettyblocks.atlassian.net/browse/TA-1882?atlOrigin=eyJpIjoiYzk5ZmI3ZWFmZWU5NGMxM2E2MWZhZmU1MTc5NDJiYmEiLCJwIjoiaiJ9).

Add item id to variables if item id exists

---

src/components/form.js
src/prefabs/dialog.js
src/prefabs/form.js

onActionDone was already PR last week. Added some tiny changes to 2 prefabs as well.

Add onActionDone interaction to form component; Removed 100px fixed height in dialog; Changed submit button default color to primary

---

src/prefabs/form.js
src/prefabs/submitButton.js

- this makes the submit button the same as normal button

fix: add icon option to submit button

---

src/components/dataTable.js
src/prefabs/dataTable.js

[Related Jira ticket](https://bettyblocks.atlassian.net/browse/TA-1647?atlOrigin=eyJpIjoiYzA0NTEyOTczYjFmNGFkYmJiMGFhNjU0M2NkZmI2MWEiLCJwIjoiaiJ9).

WIP: Add unlimited scrolling option to dataTable

---

src/prefabs/appBar.js
src/prefabs/card.js
src/prefabs/cardActions.js
src/prefabs/dialog.js

This updates the buttons external link option to accept variables in the following prefabs:
- appBar
- card
- cardActions
- dialog

fix: update external link to accept variables

---

src/components/dataContainer.js

- add onUser trigger
- add onNoUser trigger
- add onUserLoading

feat: add me interaction triggers to dataContainer

---

src/components/dataTable.js

Fixes:
- Fix  table overflow when hide search field is checked and title is present.
- Fix hidden search field not being visible also when title is present.
These are based on the [test feedback](https://bettyblocks.atlassian.net/jira/software/projects/TA/boards/73?selectedIssue=TA-1647).

dataTable fixes

---

src/components/tab.js
src/components/tabs.js
src/prefabs/tab.js
src/prefabs/tabs.js

[Jira ticket](https://bettyblocks.atlassian.net/jira/software/projects/TA/boards/73?selectedIssue=TA-1727)
- Add extra alignments for the tabs component (right and bottom). 
- Add tab icon alignment (top, right, left & bottom).
- Add ability to show all tabs for easier reorganization.

feat: add tabs alignments

---

src/components/radio.js
src/prefabs/autoComplete.js
src/prefabs/checkbox.js
src/prefabs/checkboxGroup.js
src/prefabs/form.js
src/prefabs/hiddenInput.js
src/prefabs/radio.js
src/prefabs/select.js
src/prefabs/textArea.js
src/prefabs/textField.js

also change label default values to prefab names

fix: radio default value

---

CHANGELOG.md
package.json
src/components/autoComplete.js
src/components/box.js
src/components/conditional.js
src/components/dialog.js
src/components/drawerBar.js
src/components/drawerContainer.js
src/components/expansionPanel.js
src/components/panel.js
src/components/textField.js
src/prefabs/conditional.js
src/prefabs/drawer.js
src/prefabs/drawerBar.js
src/prefabs/drawerContainer.js
src/prefabs/expansionPanel.js
src/prefabs/panel.js

* feat: add minHeight to box component
* fix: password visibility toggle
* chore(release): 1.50.1 [skip ci]
* password visibility toggle ([5aa020f](https://github.com/bettyblocks/material-ui-component-set/commit/5aa020fddeb895c1ff7e4fd2957274da72b2a164))
* chore(release): 1.51.0 [skip ci]
* add minHeight to box component ([1fb6f2f](https://github.com/bettyblocks/material-ui-component-set/commit/1fb6f2f1cc709b5f87b6d6077d32427eb717f9b4))
* fix: keep dialog mounted in dom for interactions
* chore(release): 1.51.1 [skip ci]
* keep dialog mounted in dom for interactions ([b3bb163](https://github.com/bettyblocks/material-ui-component-set/commit/b3bb163d16e8ed96fcfe81dee9411136c3e06302))
* Feat: add consistent container spacing options
* feat: add dynamic inner spacing to panel
* feat: add …

Merge acceptance to master (#586)

---

src/components/alert.js
src/components/autoComplete.js
src/components/box.js
src/components/button.js
src/components/checkboxGroup.js
src/components/conditional.js
src/components/dataList.js
src/components/dataTable.js
src/components/dateTimePicker.js
src/components/dialog.js
src/components/drawerBar.js
src/components/expansionPanel.js
src/components/fileUpload.js
src/components/grid.js
src/components/progress.js
src/components/radio.js
src/components/select.js
src/components/stepper.js
src/components/tab.js
src/components/textField.js

This pull-request follows the new best-practices for defining functions described here: https://github.com/bettyblocks/cli/wiki/Component-Interactions#custom-interactions

Remove obsolete useEffect calls

---

src/components/grid.js
src/components/list.js

add `<B.InteractionScope>` to Grid and List components

fix: add InteractionScope to grid and list

---

src/components/icon.js
src/prefabs/icon.js

feat: icon component has a link and a badge component techsup2712

feat: icon component has a link and a badge component techsup2712

---

package.json
src/prefabs/dialog.js
yarn.lock

adds interactions that allow you to close and cancel a dialog
also updates the CLI(23.19.0) for compatible validation

feat: add close and cancel interactions to dialog prefab

---

src/components/dataTable.js

Fixes the bug where a dataTable with pagination set to never, and auto load on scroll turned on would not refetch data properly after first scrolling through some data.

chore: fix refetch bug edge case

---

package.json
src/components/form.js
src/prefabs/updateForm.js
yarn.lock

- create an update form with everything configured

feat: update form prefab

---

src/components/form.js
src/prefabs/updateForm.js

- Object variable has now the name of the model label in snakecase

fix: object variable name based on model

---

src/prefabs/createForm.js

- Builders are now able to create a complete configured create form

feat: create form prefab

---

src/prefabs/createForm.js

- The select component is no longer broken if you select a list property

fix: select prefab for list prop

---

src/prefabs/createForm.js
src/prefabs/updateForm.js

- We no longer pass the complete property object but only the id en type as object

fix: pass property id instead of complete object

---

src/prefabs/createForm.js
src/prefabs/loginForm.js
src/prefabs/updateForm.js

chore: update bc titles

---

src/prefabs/loginForm.js
src/prefabs/updateForm.js

- Add info text for login and update form

chore: add info text

---

package.json
src/prefabs/loginForm.js
yarn.lock

- Builders can now use the LoginFormIcon inside the prefab

chore: add login form icon

---

src/prefabs/createForm.js
src/prefabs/loginForm.js
src/prefabs/updateForm.js

The interaction name `ToggleLoadingState` is invalid and should be
`Toggle loading state`.

fix(ART-2907): Fix interaction name.

---

src/components/button.js
src/prefabs/button.js

Reverts bettyblocks/material-ui-component-set#776 because of feedback we received. We will soon make a new iteration where we can select multiple models.

Revert "Feat/pass object variable to action ART 2871"

---

src/prefabs/loginForm.js

This change applies for the login prefab.

chore(ART-2907): Set show_password_toggle true.

---

src/components/box.js

Improve function naming & add remove function to box component

chore: add remove function to box component

---

src/components/button.js
src/prefabs/button.js

Added the ACTION_MODEL option to the button.

feat: added the ACTION_MODEL option to the button

---

package.json
src/prefabs/deleteRecord.js
yarn.lock

- Builders can now use the `deleteRecord` prefab

feat: delete record prefab

---

src/prefabs/box.js
src/prefabs/createForm.js
src/prefabs/deleteRecord.js
src/prefabs/dialog.js
src/prefabs/form.js
src/prefabs/loginForm.js
src/prefabs/updateForm.js

- Changed the default position option for all prefabs where the Box component is used

fix: changed default position in Box option for prefabs that use the Box

---

src/components/conditional.js
src/components/dataTableColumn.js
src/prefabs/dataTableColumn.js

- add isFalse and isTrue triggers to conditional component
- add visibilty interactions to tableColumn

feat(techsub-3022): conditional table columns

---

src/components/media.js
src/prefabs/media.js

The image of the media component has the option now to add a link to it

feat: added link option to an image

---

src/prefabs/dataTable.js

Add missing visibility toggle to data table prefab

missing visibilty toggle to table prefab

---

src/prefabs/dataContainer.js

Adds beforecreate to the dataContainer prefab

feat(ART-2778): add beforeCreate to dataContainer

---

src/prefabs/dataContainer.js

Update texts and small design changes

fix(ART-2778): Update texts and small design feedback

---

CHANGELOG.md
package.json
src/components/dataTable.js
src/components/menu.js
src/components/menuItem.js
src/prefabs/menu.js
src/prefabs/menuItem.js

Merge Acceptance into Edge

---

src/prefabs/dataContainer.js

To link the datacontainer to a source, it uses a component selector and
links the component using an interaction. The component is required to
have a model.

feat(ART-2777): Use component-selector & create interaction.

---

src/prefabs/dataContainer.js

Also shorten the placeholder text.

chore(ART-2777): Only send id to componentSelector.

---

src/prefabs/createForm.js
src/prefabs/deleteRecord.js
src/prefabs/updateForm.js

- The model selector validation is visible again

fix: model validations are showing correctly

---

src/prefabs/pageWithLoginForm.js

Reverts bettyblocks/material-ui-component-set#927

Revert "fix: update login page template"

---

package-lock.json
src/components/dataList.js
src/prefabs/dataList.js
src/prefabs/listWithData.js

- Add options the set column count for different screen sizes to make de grid options more user friendly
- Prevent grid cells to grow to big when searching

Responsive no code grid options for dataList 

---

src/prefabs/pageWithLoginForm.js

This styled version should replace the current Login Page Template in the Page Builder.

feat: page with login form styled - TMPLT-271

---

src/prefabs/pageWithGridAndListView.js

added outerspace to paper component

chore: added outerspace to paper component

---

src/components/rating.js
src/prefabs/rating.js

Created a new component for the default component set. It's a rating component that can be used as input in a form or it can function as a read-only element. The rating component is very flexible because many attributes can be configured. For example which icon you want to use, the amount of icons (a scale varying from 1 up to and including 10 icons), the colors of these empty and filled-in icons, and whether you want to allow e.g. a value of 3.5. So it's possible to select number as well as decimal properties.

feat: rating component - TMPLT-447

---

src/prefabs/appBar.js
src/prefabs/pageWithAppBar.js
src/prefabs/pageWithGridView.js

Page template with grid view. Currently on edge, and tested on both edge and acceptance.

Feat: page with grid view - TMPLT-442

---

src/prefabs/pageWithListView.js

Page template with list view. Currently on edge, and tested on both edge and acceptance.

Feat: page template with list view - TMPLT-444

---

src/prefabs/pageWithGridAndListView.js

Added outerSpace option to Card prefab

Feat: page with grid and list view - TMPLT-407

---

src/prefabs/pageWithMasterDetailVertical.js

Page template containing a data table and detail view, vertically oriented.

feat: page template with master detail view vertically oriented - TMPLT-404

---

src/prefabs/pageWithColumnLayout.js

Reverts bettyblocks/material-ui-component-set#1133
Cloned from edge.

Revert "Chore: fix duplicate naming"

---

src/prefabs/pageWithMasterDetailVertical.js

Cleaned up the array length checks

chore: cleaned up array length checks

---

CHANGELOG.md
package.json
src/components/autoComplete.js
src/components/dataContainer.js
src/components/dataList.js
src/components/dataTable.js
src/components/dateTimePicker.js
src/components/select.js

- datalist
- select
- autocomplete

feat: add filter interaction to data components

---

CHANGELOG.md
package.json
src/components/dataContainer.js
src/components/dataTable.js
src/components/dateTimePicker.js

acceptance into edge

---

src/components/checkbox.js
src/components/checkboxGroup.js
src/components/radio.js
src/components/select.js
src/components/textField.js

feat: add reset interaction

---

src/components/conditional.js

The conditional component now correctly updates the left and right value in the state.
PAGE-612

fix: left and right values are now getting updated

---

src/components/dateTimePicker.js
src/components/textField.js
src/prefabs/datePicker.js
src/prefabs/dateTimePicker.js
src/prefabs/decimalInput.js
src/prefabs/emailInput.js
src/prefabs/form.js
src/prefabs/loginForm.js
src/prefabs/numberInput.js
src/prefabs/priceInput.js
src/prefabs/textField.js
src/prefabs/timePicker.js
src/prefabs/updateForm.js

Add autocomplete option to:
DatePicker, DateTime, emailInput, decimalInput, numberInput, priceInput, textField and forms

add autocomplete options

---

src/components/dataContainer.js
src/components/form.js

Reverts bettyblocks/material-ui-component-set#1402

Revert "feat: removes setCurrentRecord custom functions"

---

src/prefabs/dataTable.js
src/prefabs/pageWithCreateDatatable.js
src/prefabs/pageWithCrudSlideOutPanel.js
src/prefabs/pageWithOverviewAndDetails.js
src/prefabs/pageWithSimpleDashboard.js

Adds the text overflow option to all datatables (including in page templates)

feat: add text-overflow checkbox to all datatables

---

package.json

Update the latest cli version to support the style overwrites

build: update cli version

---

CHANGELOG.md
package.json
src/components/dataContainer.js

- In this release the re fetch interaction on data tables is working again

Production release

---

CHANGELOG.md
package.json
src/components/autoComplete.js
src/components/button.js

fix: code style

---

src/components/slider.js

ChangeHandler gets triggered as soon as you drag the slider.
Added filter interaction to slider component.
To make sure not every drag triggers a change (and a query in case of the filter) I added the onChange interaction on the onChangeCommited (in stead of the onChange). See https://mui.com/api/slider/#heading-props

feat: add onchange, onchangecommit and filter interaction to slider

---

src/components/slider.js

ChangeHandler gets triggered as soon as you drag the slider.
Added filter interaction to slider component.
To make sure not every drag triggers a change (and a query in case of the filter) I added the onChange interaction on the onChangeCommited (in stead of the onChange). See https://mui.com/api/slider/#heading-props

feat: add onchange and onchangecommit to slider

---

CHANGELOG.md
package.json
src/components/tab.js
yarn.lock

Fix left alignment tabs

---

src/components/autoComplete.js

Based on material-ui  onClose documentation 
https://mui.com/api/autocomplete/

feat: added onclose trigger

---

src/components/alert.js
src/components/box.js
src/components/button.js
src/components/checkbox.js
src/components/column.js
src/components/dataContainer.js
src/components/dataList.js
src/components/dataTableColumn.js
src/components/drawerBar.js
src/components/fileUpload.js
src/components/form.js
src/components/grid.js
src/components/media.js
src/components/progress.js
src/components/select.js
src/components/slider.js
src/components/stepper.js
src/components/textField.js

- components are not being re-rendered before being mounted. This has been causing issues with interactions.
- In this ticket I have moved all custom functions into useEffects

fix: move custom functions under useEffect

---

src/components/textField.js

In some specific cases you want to set the value from another textfield based on your input. This simple interaction covers those use cases.

new setValue interaction

---

src/components/selectInput.js
src/prefabs/selectinput.tsx
src/prefabs/structures/SelectInput/index.ts
src/prefabs/structures/SelectInput/options/advanced.ts
src/prefabs/structures/SelectInput/options/index.ts
src/prefabs/structures/SelectInput/options/styles.ts
src/prefabs/structures/SelectInput/options/validation.ts

Reverts bettyblocks/material-ui-component-set#1851

Revert "Revert "Feat/v2 select input page 1562""

---

src/prefabs/structures/DateTimePicker/options/index.ts
src/prefabs/structures/DateTimePicker/options/styles.ts

- change variant and input variants
- remove redundant options

fix: re-order options

---

src/prefabs/pageWithListView.js

Added a stepper in the beforeCreate where in the first step you can configure your header and footer partials.
The seconds step is the data configuration.

chore: added partial selector and stepper

---

CHANGELOG.md
package.json
src/components/multi&CustomAutocomplete.js
src/components/multipleValuesAutocomplete.js

Reverts bettyblocks/material-ui-component-set#1965

Revert "release"

---

src/components/multi&CustomAutocomplete.js
src/components/multipleValuesAutocomplete.js
src/components/single&CustomAutocomplete.js

undone changes because this gave unexpected issues on edge & acceptance. New ticket has been created to solve these three components: https://bettyblocks.atlassian.net/browse/PAGE-1937

fix: undo changes in other autocompletes

---

package.json
src/prefabs/1column.ts
src/prefabs/2columns.ts
src/prefabs/3columns.ts
src/prefabs/4columns.ts
src/prefabs/container.ts
src/prefabs/structures/Column/index.ts
src/prefabs/structures/Column/options/advanced.ts
src/prefabs/structures/Column/options/index.ts
src/prefabs/structures/Container/index.ts
src/prefabs/structures/Container/options/advanced.ts
src/prefabs/structures/Container/options/index.ts
src/prefabs/structures/Row/index.ts
src/prefabs/structures/Row/options/advanced.ts
src/prefabs/structures/Row/options/index.ts
yarn.lock

Created the structure for the Row and Column component. the prefabs now have 4 prefabs of the 1, 2, 3 and 4 column components.

chore: converted 1column component to tsx

---

src/prefabs/structures/Box/options/advanced.ts
src/prefabs/structures/Column/options/advanced.ts
src/prefabs/structures/Container/options/advanced.ts
src/prefabs/structures/Drawer/options/advanced.ts
src/prefabs/structures/DrawerBar/options/advanced.ts
src/prefabs/structures/DrawerContainer/options/advanced.ts
src/prefabs/structures/ExpansionPanel/options/advanced.ts
src/prefabs/structures/Grid/options/advanced.ts
src/prefabs/structures/List/options/advanced.ts
src/prefabs/structures/ListItem/options/advanced.ts
src/prefabs/structures/Panel/options/advanced.ts
src/prefabs/structures/Paper/options/advanced.ts
src/prefabs/structures/Row/options/advanced.ts

Removed the ACTION_JS options from non form v2 prefabs.

chore: remove actionjs options from non form v2 components

---

src/prefabs/pageWithCardView.js

Reverts bettyblocks/material-ui-component-set#2124

Revert "Feat/implement wrapper card view tmplt 1603"

---

src/prefabs/structures/TextArea/options.ts
src/prefabs/textareainput.tsx

Add option to drag a textarea component outside a form component

fix: textarea outside form

---

package.json
src/prefabs/pageWithCardAndListView.tsx
src/prefabs/pageWithCardView.tsx
src/prefabs/pageWithListView.tsx
yarn.lock

Updated the beforeCreate and bumped the component-sdk and CLI to their latest versions

fix: update beforecreate and bump cli and sdk

---

src/prefabs/autocompleteInput.tsx
src/prefabs/checkboxinput.tsx
src/prefabs/datePickerInput.tsx
src/prefabs/dateTimePickerInput.tsx
src/prefabs/decimalinput.tsx
src/prefabs/emailinput.tsx
src/prefabs/fileUploadInput.tsx
src/prefabs/hiddeninput.tsx
src/prefabs/ibaninput.tsx
src/prefabs/imageUploadInput.tsx
src/prefabs/numberinput.tsx
src/prefabs/passwordinput.tsx
src/prefabs/phoneinput.tsx
src/prefabs/priceinput.tsx
src/prefabs/radioinput.tsx
src/prefabs/selectinput.tsx
src/prefabs/textareainput.tsx
src/prefabs/textinput.tsx
src/prefabs/timePickerInput.tsx
src/prefabs/urlinput.tsx

Got rid of irrelevant if statements.

feat: removed unused checks

---

src/prefabs/backOffice.tsx
src/prefabs/backOfficeRecordView.tsx
src/prefabs/backOfficev2.tsx
src/prefabs/pageWithCardAndListView.tsx
src/prefabs/pageWithCardView.tsx
src/prefabs/pageWithCrudDialogs.tsx
src/prefabs/pageWithCrudSlideOutPanel.tsx
src/prefabs/pageWithErrors.tsx
src/prefabs/pageWithHomepageLayout.tsx
src/prefabs/pageWithInspirationalDashboard.tsx
src/prefabs/pageWithListView.tsx
src/prefabs/pageWithLoginAndRegisterForm.tsx
src/prefabs/pageWithLoginForm.tsx
src/prefabs/pageWithOverviewAndDetials.tsx
src/prefabs/pageWithProfile.tsx
src/prefabs/pageWithRegisterForm.tsx
src/prefabs/pageWithSimpleDashboard.tsx

This commit must only be merged to edge when the base values in the IDE have been changed and approved and are on edge or acceptance.

fix: replace title4 with title1

---

src/components/button.js

Fix for the ActionButton where the AB submits a form component when the AB is inside a form component.

ActionButton fix

---

src/prefabs/ratingInput.tsx
src/prefabs/structures/RatingInput/options/index.ts

Had to update the actionProperty option to be a property option. This is so the new Question component can use the Rating component.

fix: rating component option update: actionProperty -> property

---

src/prefabs/updateForm.tsx

Removed the Datalist type from the "This page" tab in the updateform

chore: exclude datalist from compSelector

---

src/components/ratingInput.js

I'm not entirely sure if this is the right approach to fixing it, but it definitely works

feat: fix rating component outer spacing

---

src/components/textinput.js

Reverts bettyblocks/material-ui-component-set#3133

Revert "feat: make input value option work with state"

---

src/components/checkboxGroup.js

include timeout to make sure the state is uptodate before trigger the onchange interaction

fix: move onChange trigger to onchange event

---

src/components/breadcrumbs.js
src/prefabs/structures/Breadcrumbs/options/index.ts

Add the option to change the color of the separator in a breadcrumbs component

feat: add separator color option

---

src/components/dateTimePickerInput.js

Material UI's formatter doesnt work if the lengths dont match.

feat: fixed timeformat bug

---

src/components/box.js

Reverts bettyblocks/material-ui-component-set#3257

Revert "Fix zindex for box component"

---

CHANGELOG.md
package-lock.json
package.json
src/components/box.js
src/prefabs/structures/Box/options/index.ts

This feature adds a z-index option when the 'fixed' Position option is selected

Z-index option on Box component

---

package-lock.json
src/components/box.js
src/prefabs/structures/Box/options/index.ts

This feature adds a Z-index option to the box component when the static position option is not selected.

Z- index box fix [PFR-707]

---

src/components/conditional.js

https://bettyblocks.atlassian.net/jira/servicedesk/projects/PFR/queues/issue/PFR-722

fix: checks empty value in conditional contains

---

src/components/media.js

This change fixes the issue that an image from a data property or URL is not correctly displayed in runtime.

fix: correctly display image from URL in runtime

---

src/components/actionJSHiddenInput.js

The input now shows the value selected in the pagebuider. Useful if you have many hidden inputs on a page.

feat: input shows value in dev mode

---

package.json
src/components/dataList.js
src/components/dataTable.js
src/interactions/cursorToPointer.ts
src/interactions/logout.ts
src/interactions/navigateToOutputUrl.ts
src/interactions/redirect.ts
src/interactions/setCurrentRecord.ts
src/interactions/setLanguage.ts
yarn.lock

Reverts bettyblocks/material-ui-component-set#3345

Revert "Fix/set selected record interaction page 4019"

---

src/components/dataList.js
src/components/dataTable.js

This is done so that custom interactions also has access to the context directly

fix: add context to event

---

CHANGELOG.md
package.json
src/components/autocompleteInput.js
src/components/checkboxGroup.js
src/components/checkboxinput.js
src/components/dateTimePickerInput.js
src/components/fileUploadInput.js
src/components/multiAutoCompleteInput.js
src/components/radioinput.js
src/components/ratingInput.js
src/components/richTextInput.js
src/components/selectInput.js
src/components/textinput.js

Reverts bettyblocks/material-ui-component-set#3408

Revert "Revert "Release""

---

src/components/dateTimePickerInput.js
src/prefabs/structures/DateTimePicker/index.ts
src/prefabs/structures/DateTimePicker/options/validation.ts

**Date picker fixes:**
* Configurable error messages when value doesn't match validations.
* Converted hard coded “invalid input” to a configurable component option.
* Fixed disappearing helper text after an error message is shown.

feat: min and max date validation date picker PFR-824

---

src/prefabs/emptyWidget.ts
src/prefabs/structures/Box/options/index.ts

Added an empty widget component to start creating widgets more easily.
Updated box position value to relative so it adheres to z-index values.

feat: added widget component and update box position

---

CHANGELOG.md
package.json

The nrfem does not exist anymore, and thus the azure blob account is not reachable. This caused the master-pipeline to crash when trying to publish to the zones.

Release Master

---

src/components/richTextInput.js

Allows a richTextInput to be able to be cleared through an interaction.

feat(clear): added option to clear richTextInput PAGE 4805

---

src/components/richTextInput.js

E.g. when a span is used inside a strong-tag:
<strong>Hi, <span>everybody</span></strong>

chore: ensure markup attributes are passed to the children

---

src/components/dialog.js
src/components/drawerBar.js
src/prefabs/structures/Dialog/options/advanced.ts
src/prefabs/structures/Dialog/options/index.ts
src/prefabs/structures/DrawerBar/options/index.ts

For more information see [TECHSUP-10029](https://bettyblocks.atlassian.net/browse/TECHSUP-10029).

fix: add option to disable enforce focus to enable TinyMCE functionality TECHSUP-10029

---

src/components/progress.js
src/prefabs/structures/Progress/options/index.ts

See [PFR-1026](https://bettyblocks.atlassian.net/browse/PFR-1026) for more information.

feat: add border radius and lighter background color styling options PFR-1026

---

src/components/actionJSHiddenInput.js

For more information, see [PFR-1009](https://bettyblocks.atlassian.net/browse/PFR-1009).

feat: add function to set hidden input value via an interaction PFR-1009

---

src/components/dateTimePickerInput.js

For more information, see [PFR-1010](https://bettyblocks.atlassian.net/browse/PFR-1010).

feat: write selected date to page state PFR-1010

---

src/components/button.js

Fore more information see [TECHSUP-10088](https://bettyblocks.atlassian.net/browse/TECHSUP-10088).

fix: apply outer spacing to button on smaller devices TECHSUP-10088

---

src/components/radioinput.js

For more information see [PFR-1032](https://bettyblocks.atlassian.net/browse/PFR-1032).

feat: write radio input value to page state PFR-1032

---

src/components/autocompleteInput.js

which prevents unwanted clearing

fix: add debouncedCurrentValue to the condition 

---

CHANGELOG.md
package.json
src/prefabs/dialog.tsx
src/prefabs/pageWithCrudDialogs.tsx
src/prefabs/pageWithInspirationalDashboard.tsx

fix: Update prefabs using box innerspace FIG-118

---

CHANGELOG.md
package.json
src/components/autocompleteInput.js

This fixes the autocomplete, so it works correctly with the new pages-compiler

Merge acceptance into master

---

CHANGELOG.md
package.json
src/prefabs/updateForm.tsx

For more information, see [PFR-1047](https://bettyblocks.atlassian.net/browse/PFR-1047).

feat: option to add update form without configuration PFR-1047

---

src/components/tabs.js
src/prefabs/structures/Tab/options/index.ts

For more information, see [PFR-1071](https://bettyblocks.atlassian.net/browse/PFR-1071).

feat: add display logic option to Tab component PFR-1071

---

src/components/autocompleteInput.js
src/components/dateTimePickerInput.js
src/components/multiAutoCompleteInput.js
src/components/radioinput.js
src/prefabs/structures/AutocompleteInput/index.ts
src/prefabs/structures/AutocompleteInput/options/styles.ts
src/prefabs/structures/MultiAutoCompleteInput/index.ts
src/prefabs/structures/MultiAutoCompleteInput/options/styles.ts

https://bettyblocks.atlassian.net/browse/PAGE-5117
I've also renamed all occurances of placeHolderColor to placeholderColor for better consistency it also fixed autocomplete placeholder color since they mismatched.

fix: helper text and placeholder for multiple inputs PAGE-5117

---

src/components/decimalInput.js
src/prefabs/numberinput.ts
src/prefabs/structures/DecimalInput/index.ts

https://bettyblocks.atlassian.net/browse/PAGE-5498

fix: arrow-up-down and scroll events PAGE-5498

---

CHANGELOG.md
package.json
src/components/textinput.js
src/prefabs/structures/TextArea/options/index.ts

For more information, see [PFR-1077](https://bettyblocks.atlassian.net/browse/PFR-1077).

feat: add option to allow vertical resize of the multi-line text area PFR-1077

---

src/components/filterComponent.js
src/prefabs/structures/FilterComponent/options/index.ts

https://bettyblocks.atlassian.net/browse/PAGE-4508

fix: allow height and width to be used again in Filter component PAGE-4508

---

src/components/textinput.js
src/prefabs/passwordinput.ts
src/prefabs/structures/TextInput/index.ts
src/prefabs/structures/TextInput/options/styles.ts

For more information, see [TECHSUP-10645](https://bettyblocks.atlassian.net/browse/TECHSUP-10645).

fix: password component – Icon Cannot Be Removed or Styled TECHSUP-10645

---

src/components/media.js
src/prefabs/structures/Media/options/index.ts

https://bettyblocks.atlassian.net/browse/TECHSUP-10418
https://bettyblocks.atlassian.net/browse/PAGE-3579

fix: Media component doesn't reset to default width/height after clearing unit value & Parent inherit TECHSUP-10418 & PAGE-3579

---

src/prefabs/loginForm.tsx

For more information, see [PFR-965](https://bettyblocks.atlassian.net/browse/PFR-965).

feat: add loading state interactions to submit button in form prefabs PFR-965
