src/components/alert.js, src/components/box.js, src/components/breadcrumb.js, src/components/breadcrumbItem.js, src/components/button.js, src/components/checkbox.js, src/components/column.js, src/components/dataContainer.js, src/components/dataList.js, src/components/dataTable.js, src/components/dataTableColumn.js, src/components/dateTimePicker.js, src/components/divider.js, src/components/form.js, src/components/image.js, src/components/navigationBar.js, src/components/navigationItem.js, src/components/panel.js, src/components/radio.js, src/components/row.js, src/components/select.js, src/components/text.js, src/components/textField.js
Prefabs support the 'category' option, components don't.
=> Remove obsolete `category` option of components

package.json, src/components/dataContainer.js, yarn.lock
There is no need to use `ModelProvider` inside a `GetOne` helper. This is already being done in the helper itself.
=> fix: remove ModelProvider as child of GetOne helper

src/components/expansionPanel.js
change the `onClick` to the panel summary, instead of the entire panel.
=> Fix expansion panel bug TA-1854

src/prefabs/datePicker.js, src/prefabs/timePicker.js
Split up the dateTimePicker prefab into:
- DatePicker
- TimePicker
- DateTimePicker
Each prefab has the correct corresponding name, icon, type, and format.
=> feat: split up dateTimePicker to 3 prefabs, with correct options

src/components/dataContainer.js
Data container are used to create a context but you have to nest them in a column. Some times you need the data container context for the complete page and then it's easier design wise if you do not have to unnecessarily nest it in a column. Because it's no also a me container this becomes even more true. This way it also works better with drawers for example.
=> Make data container a BODY_COMPONENT

src/components/dataList.js, src/components/dataTable.js, src/prefabs/dataList.js, src/prefabs/dataTable.js
This gives the DataTable and the DataList components an extra 'When needed' option.
This way, the no-coder can decide to only show the pagination information when it's needed.
A DataTable gets 7 results from a response, and the pagination is set to show 10 records per page, making the pagination unnecessary. If 'when needed' is selected, the pagination would not be shown.
Here is the [related Jira ticket](https://bettyblocks.atlassian.net/browse/TA-1648?atlOrigin=eyJpIjoiY2Q4OWEwNjdiZDNmNGIzM2E3OTFmN2NhZDk2ODI5OWUiLCJwIjoiaiJ9).
=> Add 'when needed' option to data pagination TA-1648

src/components/dataTable.js
Previously, **if a model was selected on a dataTable**, and the `rowsPerPage` option was changed, these changes wouldn't show in the pagination section of the component without a page refresh.
With this PR the component now listens for changes made to the `takeNum` and updates the `setRowsPerPage` accordingly, without any refresh of the page needed.
=> Show correct rows per page selection, even when model is selected.

src/components/dataTable.js
Makes `offset` dynamic, making the fetch happen when scroll is 80% through content.
=> fix: make offset dynamic

src/components/alert.js, src/components/column.js, src/prefabs/1column.js, src/prefabs/2columns.js, src/prefabs/3columns.js, src/prefabs/4columns.js, src/prefabs/dialog.js, src/prefabs/panel.js, src/prefabs/paper.js
This fix will not render invisible components any more. On the canvas it will have to render 1 HTML element for the DND behaviour though.
Also, the key `show` is renamed to `visible` for consistency in our components/prefabs.
=> fix: dont render invisible components

src/components/box.js
Fixes TA-1946 by setting the min-height of the box to 0.
=> feat: add minHeight to box component

src/components/autoComplete.js
Tested on edge.
Labels (multiselect option) get selected in autocomplete when putting an array like ["a","b"] as a default value.
As well as ID's or anything that aligns with the Property value
=> fix: autocomplete multiselect labels are selected with default value

src/components/appBar.js
=> fix: use color setting in appbar title when link is set (fixes #649)

src/prefabs/dataTable.js
remove default value of empty string since its no longer required
=> fix: remove empty string from properties list

src/components/dataTableColumn.js
Reverts bettyblocks/material-ui-component-set#714
We have a better fix in the compiler. So this solution is no longer required
=> Revert "fix: onRowClick has no event object"

src/components/tab.js, src/components/tabs.js, src/prefabs/tab.js, src/prefabs/tabs.js
Fixes a bug where tabs and tab component cannot be set to stretch full height of their parent
/src/components/tabs
/src/prefabs/tabs
/src/components/tab
/src/prefabs/tab
Add to a drawer one tabs component set height to 100%, add a tab component inside the tabs and set it's height to 100% add a box inside the tab and set it's height to 100% the box and the tabs should be full height of the drawer.
Potential side-effects introduced by this behaviour
Resolves WORK-8
=> fix: added height to tabs and tab component

src/prefabs/createForm.js, src/prefabs/updateForm.js
- We no longer pass the complete property object but only the `id` en `type` as value
=> fix: pass property id instead of complete object

src/prefabs/loginForm.js
When logging in, it is not required to enter a password with x
characters, a number and a capital letter. This commit removes the
validation.
=> fix(ART-2906): Remove validation from password field.

package.json, yarn.lock
Prefab didn't change itself, only the CLI version has been changed in order to automatically upload page prefabs when releasing.
=> chore: update cli version for upload page prefabs

src/components/box.js, src/prefabs/deleteRecord.js
- Users can now see the dialog correctly inside the deleteRecord prefab
=> fix: dialog component not being shown correctly inside the box component

src/prefabs/deleteRecord.js
- Use the modelName instead of the modelLabel because in the runtime artifact only the modelName is available.
=> fix: use model_name for the variable name instead of the label

src/components/dialog.js, src/prefabs/dialog.js
Add toggle to dialog to disable backdrop click so people can not close dialog by clicking outside of it
=> feat: disable backdrop click for dialog

src/components/dataTableColumn.js
This fix makes sure that you do not get a "Endpoint does not exist in artifact" error when you disable the Row click endpoint on the dataTable
https://bettyblocks.atlassian.net/browse/TECHSUP-3146
=> fix row click endpoint leads to compile error

src/components/dataTable.js, src/prefabs/dataTable.js
A feature request from multiple self-building (consultancy) customers was the option to have striped DataTables. An option was added to make the table striped and also an option to select the color.
=> added striped option

src/components/autoComplete.js, src/components/button.js
Fixes the href error in the button:
Fixes the loading prop (which is not supported) in autocomplete:
Fixes the presence of the non existing prop PopoverProps in autocomplete:
Fixes the attempt to mutate a non mutable object in the autocomplete (the filter):
=> fix: autocomplete filter assignment and css props

src/components/dataTable.js
This reverts commit 96f8c1841afa8694c0573eb5da88cd13eb483af5.
Filter should work with blank values
=> Revert "fix: autoselect doesn't crash when clearing the textfield"

src/components/checkbox.js
Use case: 
In my application I want to conditionally enable a checkbox component based on the role of the current user. The checkbox should be disabled by default, but I want to trigger the Enable component function via a conditional component when the user has role X (there are also other interactions triggered by this conditional). The Enable/Disable component functions can currently only be used together with for example the Button and TextField component.
There is currently a workaround where you will have to place two different checkbox components and two parent conditional components on the page. A single interaction in combination with a single checkbox would be a cleaner solution in my opinion.
=> Feat: add enable and disable interactions to checkbox PFR-401

src/components/autoComplete.js, src/prefabs/autoComplete.js
Builders are using the "freesolo" option just to remove the "--empty--" option that is being displayed for the single value autocomplete.
Also removed the "freesolo" option as it was unclear what it was used for and adds a lot of complexity
=> fix: prevent empty option based on the default prefab empty string

src/components/dateTimePicker.js
- onChange event is only sent on valid or empty input
=> fix: DateTimePicker breaks on keyboard input

src/components/button.js
This fixes the cursor to change to 'pointer' when hovering over the entire button, not just the text.
=> chore: move cursor property to customStyles

src/components/tabs.js, src/prefabs/tabs.js
Example: 
Your tabs component has 5 tabs. Tab 1 opens on page load, but you got feedback on tab 3.
Current situation: 
1. Navigate to tabs component en set the 'Selected tab index' on tab 3.
2. Make changes on tab 3
3. Navigate to tabs component en set the 'Selected tab index' on tab 1. (This step is comon to forget, so after you merge it to the next environment you'll receive feedback that the tabs component opens on tab 3 instead on tab 1)
4. Compile page
5. Click on tab 3 en test your changes
New situation:
1. Navigate to tabs component en set the 'Selected development tab index' on tab 3.
2. Make changes on tab 3
3. Compile page
4. Click on tab 3 en test your changes
The new situation improves the development speed, the developer happiness and les unnecessary feedback.
=> feat: add development tab option

src/components/dateTimePickerInput.js
- mysql it's own set of datetime formats, none of
which are compatible with javascripts ISO8601
=> fix: datetime format

.github/workflows/publish_production.yml, CHANGELOG.md, package.json
This adds a button to the GitHub interface and allows the production publish workflow to be run manually.
I made the PR because of an issue we came across today and we thought we would need it, but it wasn't necessary in the end. Still it couldn't hurt to have!
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
Let me know if you guys agree :)
=> Ci/allow publish action dispatch from GitHub page 1337

src/prefabs/checkboxinput.tsx, src/prefabs/hiddeninput.tsx, src/prefabs/structures/AutocompleteInput/index.ts, src/prefabs/structures/DateTimePicker/index.ts, src/prefabs/structures/MultiAutoCompleteInput/index.ts, src/prefabs/structures/RadioInput/index.ts, src/prefabs/structures/SelectInput/index.ts, src/prefabs/structures/TextInput/index.ts
Components that have been duplicated, by duplicate-page for example,
point to the original ActionVariable, instead of the duplicate
ActionVariable. Meaning that after delete, a mutation to the MetaAPI is
been made to delete the wrong actionVariable.
This commit removes the afterDelete deleteActionVariable from the
components.
In the MetaAPI, we have applied changes - with the same jira-tag:
PAGE-2170 - which changed the logic of deleting an component. Now, when
you delete a component, and the component points to an actionVariable,
it will also delete the actionVariable. The actionVariableId used in the
MetaAPI points to the correct actionVariable: the duplicated one.
=> Fix(PAGE-2170): Remove afterDelete 'deleteActionVariable' from components.

src/prefabs/backOffice.tsx, src/prefabs/pageWithCrudSlideOutPanel.tsx
Currently the MetaAPI mutation schema only allows `strings` for the input-field `value`. This commit will change the boolean value to a string value.
=> fix: Change boolean to string for allowed_input.

src/interactions/setUrlParameter.ts, src/prefabs/structures/TextInput/options/advanced.ts
The combination of this interaction and the search paramater option adds or updates that search paramater with the value of the input component. 
This way it can be used to dynamically add search paramaters for endusers via the url to for example search on title OR description.
=> feat: add interaction to set search parameters

CHANGELOG.md, package.json, src/components/dataList.js, src/prefabs/backOffice.tsx, src/prefabs/backOfficeDetailsv2.tsx, src/prefabs/backOfficev2.tsx
In case you have a data list of 5 records and the pagination component option is set to "When needed" and the rows per page is equal to 5, no pagination is shown. When you add a new (6th) record via a form/action button and trigger a refetch on the data list, the pagination will now show up since you'll have two pages to show. On the contrary, when you have 6 records and delete one, the pagination will disappear.
=> fix: setShowPagination (in case of "When needed") to false OR true

src/components/dateTimePickerInput.js
When using a default value with the following format "MM-dd-yyyy" (which is the default that is set when dragging a datepicker on the canvas) the value is not shown. This is because the format in the parse helper function of DateFNS is hard-coded set to "yyyy-MM-dd" which does not match. This feature passes the format value from the component option to the parse helper function in order to work.
=> fix: use correct format to set the default value

src/components/dataContainer.js, src/prefabs/structures/DataContainer/options/advanced.ts, src/prefabs/structures/DataContainer/options/index.ts
Hey! :wave: 
I've made the fetch policy configurable for a dataContainer component. This adds the following options under the advanced category:
- Cache => [cache-and-network](https://www.apollographql.com/docs/react/data/queries/#cache-and-network) (This was the default previously, and will still be used by default)
- No cache => [no-cache](https://www.apollographql.com/docs/react/data/queries/#no-cache)
This way it stays simple for the no-coder, and backwards compatible if we do end up deciding to support more fetch policies.
This is to fix an issue a client is running into: [Ticket 2887](https://bettyblocks.atlassian.net/browse/PAGE-2882?atlOrigin=eyJpIjoiOTNhMzkxMzE1MWQ3NGZlZTg1OTM1YjhkYjIyNTRhZjkiLCJwIjoiaiJ9)
Read the comments of this ticket for more understanding why we chose to go …
=> feat: make fetch policy configurable

src/components/text.js, src/prefabs/structures/Text/options/index.ts
This was a feature request from Chris. There was already a branch for this, but the branch was outdated and it had a lot of changes which already were on production. https://github.com/bettyblocks/material-ui-component-set/pull/2782
=> feat: add theme weight to text component

src/prefabs/emailinput.tsx
This new regex will also accept capitals in your email. For example: Firstname.Lastname@bettyblocks.com This was not the case with the previous regex. I've heard clients which also use capitals within their email address which walk into errors al the time.
=> Added capitals to validation for email input

src/components/dateTimePickerInput.js
The ISO-format contains timezone information.
This will solve a bug where entering a datetime in a browser in another timezone as the server, would result in a timejump when requesting the datetime.
=> feat: Store datetime in ISO-format

src/interactions/login.ts
Allowing to login via only one profile at a time, will prevent confusion in the /me-query. This query would often use the wrong keys, when multiple keys were present, and show unexpected behaviour.
=> feat: remove betty-jwt cookie, when logging in via user/password

src/components/tabs.js
In design time you always want to see the child components of the tabs.
https://bettyblocks.atlassian.net/browse/PAGE-3378
=> fix: preload data in design time or option is true

src/components/conditional.js
Comparing empty with empty (when both left- and righthand side are empty) would result in `false`, instead of `true`. This was because JS is stupid, and said that an empty string can be converted to a number, but then returned a `nil`.
=> fix: conditional can handle empty values

CHANGELOG.md, package.json, src/components/dataList.js, src/components/dataTable.js, src/prefabs/structures/DataList/options/index.ts, src/prefabs/structures/DataTable/options/index.ts
Currently, there is no option in a Data List or Data table PB component to show a (default) message when there are no results fetched from the Data API. The only way to properly show that there are no results, is to use an “OnNoResults” interaction in combination with a Conditional component and a Text component. By adding a variable option to these two Data components, builders can save an interaction and (at least) two additional components for each Data List/Table which can help reduce the page complexity.
=> feat: add option to show text when no results fetched PFR-697

src/components/dataTable.js
Makes sure that the message takes over all columns in the data table (i.e. 100% width) when there are no results, instead of cropping the message inside the first column when there are multiple column inside the table.
=> fix: no results message stretches to table width

src/components/textinput.js, src/prefabs/structures/TextInput/index.ts, src/prefabs/structures/TextInput/options/advanced.ts
Added a debounce delay option under Advanced which allows you to set a delay before the onChange interaction is triggered. Use cases are described in [the PFR ticket](https://bettyblocks.atlassian.net/browse/PFR-412). Code was generated with the help of AI. It makes use of the useRef hook to maintain a consistent debounced function across (re-)renders.
=> feat: add debounceDelay option for onChange text input

src/components/multiAutoCompleteInput.js
When the chips in the autocomplete have a dark background color, the delete icon is not (clearly) visible.
If the background color is dark, you will apply a light color to the text within the chip and the icon should behave the same. By default, the background color of the chip is set to Light (from the theme builder). The default Material UI color for the delete icon is fine then, but as soon as the background color of the chip is changed the icon color should be the same as the text color. This was a finding when working with the design system from the police. The UI was agreed upon with UX.
=> fix: improve visibility of delete icon in chips autocomplete

CHANGELOG.md, package.json, src/components/dialog.js, src/components/radioinput.js, src/components/selectInput.js, src/prefabs/pageWithQuestionnaireStart.tsx, src/prefabs/questionnaire/dropdownWidget.ts, src/prefabs/questionnaire/radioWidget.ts, src/prefabs/radioinput.tsx, src/prefabs/selectinput.tsx, src/prefabs/structures/Dialog/options/advanced.ts, src/prefabs/structures/Dialog/options/index.ts
Let’s say you have a Dialog on your page that is initially hidden. All child components inside the Dialog that request data (like a Form, Data Container, (Multi) Autocomplete, Data List or Data Table) do fire calls to the Data API despite that they are not even visible. This PR adds an option to the Dialog component to disable preloading all child components to prevent unnecessary Data API calls.
[PFR-764](https://bettyblocks.atlassian.net/browse/PFR-764)
=> feat: allow to disable preload children in dialog PFR-764

src/components/textinput.js, src/prefabs/structures/TextInput/index.ts, src/prefabs/structures/TextInput/options/advanced.ts
Added a debounce delay option under Advanced which allows you to set a delay before the onChange interaction is triggered. Use cases are described in [the PFR ticket](https://bettyblocks.atlassian.net/browse/PFR-412). Code was generated with the help of AI. It makes use of the useRef hook to maintain a consistent debounced function across (re-)renders.
=> Feat: add debounce delay on change interaction textinput PFR-412

src/components/drawer.js
Before fix: The drawerbar would always be visible when the 'RESPONSIVELY TEMPORARY ON' option was set to 'mobile' and the 'INITIAL STATE (RUNTIME)' option was set to hidden.
For more details, see this ticket below
Ticket url: https://bettyblocks.atlassian.net/browse/PRDGM-191
=> fix: initial responsive state mobile hidden

src/components/dataTable.js
This fix makes sure the error message is entirely shown in the header of the data table component. An example of the current (before) and new (after) situation can be seen in [PFR-727](https://bettyblocks.atlassian.net/browse/PFR-727).
=> fix: properly display error msg in data table header PFR-727

src/components/textinput.js
Currently when using the email input the validation message is not showing. It appears that the validation is being done on the type instead of the regex. This fix makes sure the regex is used.
=> bugfix in email input where the validation message is not showing

src/components/avatar.js
Currently you’re only able to change the font size of the text and it’s not possible to change the font size of the icon.
A page design often includes a list of people with profile pictures, and a fallback image/icon should be used in case there is no image present. If the size of the avatar is somewhat bigger than the default, the icon size does not really match because it always stays the same size. 
This PR adds the ability to change the font size of the icon with the existing font size component option.
Link to PFR ticket: [PFR-788](https://bettyblocks.atlassian.net/browse/PFR-788).
=> feat: add CSS rule for icon font size in avatar PFR-788

src/components/dataContainer.js
type option
This is so that even if the loading type is set to content, it respects the wait for request setting
=> fix: make the wait for request option work together with the loading

src/components/menu.js, src/components/menuItem.js, src/prefabs/structures/MenuItem/options/index.ts
The default behavior of the MUI Menu Item component is that the background color changes on hover, but due to a CSS rule in the styles section of the component this hover feedback is not present. In design time you don’t want to see any feedback on click or on hover, but in runtime you do want to see this. This PR fixes both visual issues. Additionally, an option has been added to change the color of the icon independently of the text.
A link to the MUI Menu component: [React Menu component - Material UI](https://mui.com/material-ui/react-menu/).
A link to the PFR ticket: [PFR-781](https://bettyblocks.atlassian.net/browse/PFR-781).
=> fix: click and hover feedback menu component PFR-781

src/prefabs/backOffice.tsx
The "onActionDone" interaction trigger doesn't work so I replaced it with two interactions: "onActionSuccess" and "onActionError" to re-enable the submit button after an error has occurred.
=> fix: replace onActionDone trigger by onActionSuccess and onActionError

src/components/fileUploadInput.js, src/prefabs/imageUploadInput.tsx, src/prefabs/structures/FileUpload/index.ts, src/prefabs/structures/FileUpload/options/styles.ts
When you have an Image Upload or File Upload component on a page where Light is used as background color, the delete icon for removing the uploaded image or file is not visible because it uses the same theme color.
The color of the delete icon should be configurable via a component option instead of always taking the Light color from the theme builder.
Link to the PFR ticket: [PFR-809](https://bettyblocks.atlassian.net/browse/PFR-809).
=> fix: make delete icon color of Image/File Upload configurable through component option PFR-809

src/components/fileUploadInput.js
The file reference of the uploaded file is stored in state. However, the onSuccess trigger event is fired before this value is actually stored in state. This fix makes sure that the onSuccess trigger event is fired when the file reference value in state has changed.
=> fix: trigger onSuccess event after file reference is successfully stored

src/components/fileUploadInput.js
The file reference of the uploaded file is stored in state. However, the onSuccess trigger event is fired before this value is actually stored in state. This fix makes sure that the onSuccess trigger event is fired after the file reference value in state has changed and stored in the hidden input.
=> fix: trigger onSuccess event after file reference is successfully stored PFR-845

src/components/tabs.js
This fix makes sure the active tab indicator is shown on page load. For more information, see [TECHSUP-8534](https://bettyblocks.atlassian.net/browse/TECHSUP-8534).
=> fix: manually trigger updateIndicator to show active tab on page load TECHSUP-8534

src/components/tabs.js
This fix makes sure the active tab indicator is shown on page load. For more information, see [TECHSUP-8534](https://bettyblocks.atlassian.net/browse/TECHSUP-8534) or the thread in [my previous PR to edge](https://github.com/bettyblocks/material-ui-component-set/pull/3426).
=> fix: show active tab indicator on page load TECHSUP-8534

src/components/box.js, src/prefabs/structures/Box/options/index.ts
This feature adds a new component option for selecting a public file as background image so that the image URL is always the one of the current environment, see [PFR-680](https://bettyblocks.atlassian.net/browse/PFR-680) for a more detailed explanation.
It also fixes the existing component interactions ("setCustomBackgroundImage" and "removeCustomBackgroundImage") that were not working anymore.
=> feat: select public file as background image box component PFR-680

src/components/dateTimePickerInput.js, src/prefabs/monthPickerInput.tsx, src/prefabs/structures/DateTimePicker/index.ts, src/prefabs/structures/DateTimePicker/options/index.ts
A new prefab called **Month picker** which is based on the Date picker component and meant for a user to select an available Month only. Material UI offers the [“views” prop](https://mui.com/x/react-date-pickers/date-picker/#views) that makes it easy to configure the selection views in the pop up (which is one of “date”, “year”, “month”, “day” “hours”, “minutes”, “seconds” depending on the type of the picker).
In this PR the "views" array is provided for each prefab type so that it can easily be (re)configured in the future. For example, you currently can’t select the seconds by default with the Time picker because it is not included in the views array by default, but the seconds will be shown in the input because of the default format option value “HH:mm:ss“. You could either remove …
=> feat: month picker component PFR-643

src/components/checkboxinput.js, src/components/fileUploadInput.js, src/components/textinput.js
+ When a datatable or a datalist triggers the refetch interaction, some components do not update their value. This fix will ensure that the state will be update with the new value
=> fix: rerender components when initial value changes

src/components/autocompleteInput.js, src/prefabs/autocompleteInput.tsx
The autocomplete component should now show its default value and other records from its filter:
And when searching it searches through all records or records within it's filter:
=> fix: add default value to current filter and show remaining records

src/components/textinput.js, src/prefabs/structures/TextInput/options/validation.ts
This feature includes a new checkbox component option to set auto focus on an input on page load, and an interaction called `Focus` to focus on an input field. When the component option is set to true for multiple inputs, only the last input will be focused on.
`const focusHandler = () => setTimeout(() => { inputRef.current.focus(); }, 0);`
[A late timeout](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#:~:text=for%20more%20details.-,Late%20timeouts,-The%20timeout%20can) is required to be able to trigger the focus interaction on inputs that are inside Dialog or DrawerSidebar components.
Link to the PFR ticket: [PFR-899](https://bettyblocks.atlassian.net/browse/PFR-899).
=> feat: set focus to text input component PFR-899

src/prefabs/pageWithErrors.tsx, src/prefabs/pageWithHomepageLayout.tsx, src/prefabs/pageWithLoginAndRegisterForm.tsx, src/prefabs/pageWithLoginForm.tsx, src/prefabs/pageWithRegisterForm.tsx
For page-prefabs.
The backgroundType default is set to 'img', but is needed to be 'url' since it points to assets.
=> fix(PAGE-4710): Background image of box are now shown

.github/workflows/publish_bundle_production.yml, .github/workflows/publish_production.yml
The nrfem does not exist anymore, and thus the azure blob account is not reachable. This caused the master-pipeline to crash when trying to publish to the zones.
=> fix(PAGE-4710): Remove unused zone from publish prod files.

src/components/dateTimePickerInput.js
This is to prevent the label to fall over the content, when the date / time / datetime is selected via the modal-picker
=> fix: force floatingLabel when a value is present in dataPicker

src/components/dateTimePickerInput.js
This will trigger a 'field has changed' event in MUI, and force the label to go up when the picker-modal is opened.
This is a better solution than forcing the label to go above the field, so those changes from the previous commit have been reversed.
=> fix: give datePickerField a default value of null

src/components/checkboxinput.js, src/components/ratingInput.js, src/components/textinput.js
The reversed code solved a bug that only occured when the input-component was iterated. When a component is iterated, it would trigger some code in the compiler that didn't perfectly handle the state.
But the solve broke a use-case, where component is in a conditional, and the state is persisted when the component is temporarily not on the page.
By reverting this code, and fixing the compiler, all use-cases now work.
=> fix: rely on use-page-state to get the current value

src/components/selectInput.js
There is currently only [a handful of components](https://github.com/search?q=repo%3Abettyblocks%2Fmaterial-ui-component-set%20path%3A%2F%5Esrc%5C%2Fcomponents%5C%2F%2F%20usePageState&type=code) (RatingInput, CheckboxInput, TextInput, DataList and DataTable) that can hold a value in the page state. It would be nice to add the SelectInput component to that collection, because I came across a use case where it was needed.
See [PFR-924](https://bettyblocks.atlassian.net/browse/PFR-924) for more information.
=> feat: include value of Select component in page state PFR-924

src/components/dataContainer.js
Currently, the option "Redirect when no result" does not work in combination with an authentication profile which leads to confusion and unnecessary workarounds. This fix enables the builder to use the "Redirect when no result" option when using an authentication profile as well.
The TECHSUP ticket: [TECHSUP-9627](https://bettyblocks.atlassian.net/browse/TECHSUP-9627).
=> fix: make "Redirect when no result" option work with auth profile TECHSUP-9627

src/components/expansionPanel.js, src/prefabs/structures/ExpansionPanel/options/index.ts
This pull request includes the following features:
- The option to set a different dropdown icon. In the current Material UI set there are 4 options: "ArrowDownward", "ArrowDropDown", "ArrowDropDownCircle", and "ExpandMore".
- The option to change the position of the icon. Either show the dropdown icon at the start or at the end.
- The option to change the color of the icon. In some designs you need to adjust the color to the customer's theming.
Link to the PFR ticket: [PFR-952](https://bettyblocks.atlassian.net/browse/PFR-952).
=> feat: add icon, icon position and icon color options to expansion panel PFR-952

src/components/actionJSButton.js, src/components/button.js
Full width is correctly applied to the default button, open page button and logout button. Only the submit button and action button show unexpected behavior. The exact same CSS rule is applied to make it consistent (copied from the `linkComponent` style: https://github.com/bettyblocks/material-ui-component-set/blob/5b06a333152539d1b1cc7ae855b535f2d872fe50/src/components/button.js#L316-L321). 
See [TECHSUP-10124](https://bettyblocks.atlassian.net/browse/TECHSUP-10124) for more information.
=> fix: apply full width to submit and action buttons on smaller devices TECHSUP-10124

src/components/selectInput.js
Parse the default value of the Select input component to a number. Another value than number (e.g. "null" or "test") will be  parsed to an empty value. This fixes an issue where the onChange is triggered twice, see the TECHSUP ticket.
Link to TECHSUP ticket: [TECHSUP-10003](https://bettyblocks.atlassian.net/browse/TECHSUP-10003)
=> fix: parse default value of Select input to number value TECHSUP-10003

src/components/tabs.js
This reverts issue PAGE-3551, but when testing this ticket it doesn't occur anymore when using flex. When PAGE-3551 occurs again, we may need to enrich the alignment configuration.
=> fix: use display flex for tabs so left side tabs don't push content down

package.json, src/prefabs/numberinput.ts, src/prefabs/questionnaire/numberWidget.ts, src/prefabs/structures/DecimalInput/index.ts, src/prefabs/structures/DecimalInput/options/index.ts, yarn.lock
By using the Decimal component with a scale of 0 we ensure it is a number input which has options for number based components
=> fix: min and max values should be validated in a number input

src/components/autocompleteInput.js
When used in the pages-compiler, this component keeps rendering because of all the state updates. To avoid this cyclic rerender without rewriting the whole component, I added a condition to the onInputChange function. Apparently this gets `event: null` on state updates.
=> fix: prevent cyclic render loop by catching the event on state updates

src/components/expansionPanel.js
For more information, see [TECHSUP-10401](https://bettyblocks.atlassian.net/browse/TECHSUP-10401).
=> fix: always show data when expansion panel expands via interactions TECHSUP-10401

src/components/autocompleteInput.js
When rerendering, the currentValue becomes null. This causes the hidden input to have an empty value in unexpected moments. This fix prevents that behavior.
=> fix: dont clear the value in autocomplete while rerendering

src/components/expansionPanel.js
For more information, see [TECHSUP-10401](https://bettyblocks.atlassian.net/browse/TECHSUP-10401).
=> fix: always show data when expansion panel expands via interactions

CHANGELOG.md, package.json, src/components/autocompleteInput.js
This condition is added for using the pages compiler.
It prevents unwanted clearing of the value, however it should clear when using the clear interaction.
=> fix: add debouncedCurrentValue to the autocomplete condition 

src/components/menu.js
* Bonus: the CSS rule `text-transform: none;` allows you to have a menu button without all uppercased characters.
For more information, see [PFR-1062](https://bettyblocks.atlassian.net/browse/PFR-1062).
=> feat: allow BODY_COMPONENT and CONTAINER_COMPONENT types as children in Menu PFR-1062

src/components/alert.js, src/prefabs/structures/Alert/options/index.ts
Added a checkbox option "Display Rich Text" to the Alert, similar to the checkbox option in [the Text prefab](https://github.com/bettyblocks/material-ui-component-set/blob/d5d1b3e754567d12816bec7a47fcc15c9f5f7de2/src/prefabs/structures/Text/options/index.ts#L33). With this option, you are able to return rich text from the action, and show it as HTML content in the Alert. For example, to highlight certain words or to include an inline text link.
Link to the PFR ticket: [PFR-945](https://bettyblocks.atlassian.net/browse/PFR-945).
=> feat: add "Display Rich Text" checkbox option to dynamically show HTML content PFR-945

src/components/button.js
After implementing https://github.com/bettyblocks/material-ui-component-set/pull/3747, the OnClick trigger does not work anymore for the submit button. This change makes sure to enable this feature again.
For more information, see [PFR-929](https://bettyblocks.atlassian.net/browse/PFR-929) & [PFR-1075](https://bettyblocks.atlassian.net/browse/PFR-1075).
=> feat: trigger onClick interaction for submit and action button PFR-929 & PFR-1075
